// src/constants/visualTrainingData.ts
import { PlaceType } from "./trainingData";
export const VISUAL_MATCHING_PROTOCOLS: Record<string, any> = {
  home: [
    {
      id: 1,
      targetWord: "가위",
      options: [
        { id: "a", label: "꽃", emoji: "🌻" },
        { id: "b", label: "빗", emoji: "🪮" },
        { id: "c", label: "가위", emoji: "✂️" },
        { id: "d", label: "연필", emoji: "✏️" },
        { id: "e", label: "컵", emoji: "🥛" },
        { id: "f", label: "손톱깎이", emoji: "💅" },
      ],
      answerId: "c",
    },
    {
      id: 2,
      targetWord: "냉장고",
      options: [
        { id: "a", label: "세탁기", emoji: "🧺" },
        { id: "b", label: "냉장고", emoji: "🧊" },
        { id: "c", label: "에어컨", emoji: "❄️" },
        { id: "d", label: "선풍기", emoji: "🌀" },
        { id: "e", label: "전자레인지", emoji: "📻" },
        { id: "f", label: "텔레비전", emoji: "📺" },
      ],
      answerId: "b",
    },
    {
      id: 3,
      targetWord: "침대",
      options: [
        { id: "a", label: "의자", emoji: "🪑" },
        { id: "b", label: "책상", emoji: "🪵" },
        { id: "c", label: "소파", emoji: "🛋️" },
        { id: "d", label: "침대", emoji: "🛏️" },
        { id: "e", label: "옷장", emoji: "🚪" },
        { id: "f", label: "서랍", emoji: "🗄️" },
      ],
      answerId: "d",
    },
    {
      id: 4,
      targetWord: "수건",
      options: [
        { id: "a", label: "수건", emoji: "🧴" },
        { id: "b", label: "비누", emoji: "🧼" },
        { id: "c", label: "칫솔", emoji: "🪥" },
        { id: "d", label: "치약", emoji: "🦷" },
        { id: "e", label: "샴푸", emoji: "🧴" },
        { id: "f", label: "거울", emoji: "🪞" },
      ],
      answerId: "a",
    },
    {
      id: 5,
      targetWord: "열쇠",
      options: [
        { id: "a", label: "지갑", emoji: "👛" },
        { id: "b", label: "열쇠", emoji: "🔑" },
        { id: "c", label: "시계", emoji: "⌚" },
        { id: "d", label: "안경", emoji: "👓" },
        { id: "e", label: "휴대폰", emoji: "📱" },
        { id: "f", label: "우산", emoji: "☂️" },
      ],
      answerId: "b",
    },
    {
      id: 6,
      targetWord: "빗자루",
      options: [
        { id: "a", label: "청소기", emoji: "🧹" },
        { id: "b", label: "빗자루", emoji: "🧹" },
        { id: "c", label: "걸레", emoji: "🧽" },
        { id: "d", label: "쓰레받기", emoji: "🗑️" },
        { id: "e", label: "세제", emoji: "🧴" },
        { id: "f", label: "양동이", emoji: "🪣" },
      ],
      answerId: "b",
    },
    {
      id: 7,
      targetWord: "리모컨",
      options: [
        { id: "a", label: "리모컨", emoji: "📱" },
        { id: "b", label: "충전기", emoji: "🔌" },
        { id: "c", label: "건전지", emoji: "🔋" },
        { id: "d", label: "전선", emoji: "🔌" },
        { id: "e", label: "콘센트", emoji: "🔌" },
        { id: "f", label: "전구", emoji: "💡" },
      ],
      answerId: "a",
    },
    {
      id: 8,
      targetWord: "그릇",
      options: [
        { id: "a", label: "냄비", emoji: "🍲" },
        { id: "b", label: "프라이팬", emoji: "🍳" },
        { id: "c", label: "그릇", emoji: "🥣" },
        { id: "d", label: "젓가락", emoji: "🥢" },
        { id: "e", label: "숟가락", emoji: "🥄" },
        { id: "f", label: "포크", emoji: "🍴" },
      ],
      answerId: "c",
    },
    {
      id: 9,
      targetWord: "베개",
      options: [
        { id: "a", label: "이불", emoji: "🛏️" },
        { id: "b", label: "베개", emoji: "🛌" },
        { id: "c", label: "담요", emoji: "🧣" },
        { id: "d", label: "매트리스", emoji: "🛏️" },
        { id: "e", label: "시트", emoji: "🧻" },
        { id: "f", label: "커튼", emoji: "🪟" },
      ],
      answerId: "b",
    },
    {
      id: 10,
      targetWord: "슬리퍼",
      options: [
        { id: "a", label: "운동화", emoji: "👟" },
        { id: "b", label: "구두", emoji: "👞" },
        { id: "c", label: "샌들", emoji: "🩴" },
        { id: "d", label: "슬리퍼", emoji: "🩴" },
        { id: "e", label: "장화", emoji: "🥾" },
        { id: "f", label: "양말", emoji: "🧦" },
      ],
      answerId: "d",
    },
  ],
  hospital: [
    {
      id: 1,
      targetWord: "청진기",
      options: [
        { id: "a", label: "청진기", emoji: "🩺" },
        { id: "b", label: "주사기", emoji: "💉" },
        { id: "c", label: "체온계", emoji: "🌡️" },
        { id: "d", label: "붕대", emoji: "🩹" },
        { id: "e", label: "약병", emoji: "💊" },
        { id: "f", label: "휠체어", emoji: "🦽" },
      ],
      answerId: "a",
    },
    {
      id: 2,
      targetWord: "주사기",
      options: [
        { id: "a", label: "청진기", emoji: "🩺" },
        { id: "b", label: "주사기", emoji: "💉" },
        { id: "c", label: "체온계", emoji: "🌡️" },
        { id: "d", label: "알약", emoji: "💊" },
        { id: "e", label: "반창고", emoji: "🩹" },
        { id: "f", label: "마스크", emoji: "😷" },
      ],
      answerId: "b",
    },
    {
      id: 3,
      targetWord: "체온계",
      options: [
        { id: "a", label: "혈압계", emoji: "🩸" },
        { id: "b", label: "체중계", emoji: "⚖️" },
        { id: "c", label: "체온계", emoji: "🌡️" },
        { id: "d", label: "산소포화도계", emoji: "💓" },
        { id: "e", label: "심전도기", emoji: "💗" },
        { id: "f", label: "엑스레이", emoji: "🦴" },
      ],
      answerId: "c",
    },
    {
      id: 4,
      targetWord: "휠체어",
      options: [
        { id: "a", label: "목발", emoji: "🦯" },
        { id: "b", label: "휠체어", emoji: "🦽" },
        { id: "c", label: "침대", emoji: "🛏️" },
        { id: "d", label: "들것", emoji: "🛏️" },
        { id: "e", label: "지팡이", emoji: "🦯" },
        { id: "f", label: "보행기", emoji: "🚶" },
      ],
      answerId: "b",
    },
    {
      id: 5,
      targetWord: "알약",
      options: [
        { id: "a", label: "물약", emoji: "🧪" },
        { id: "b", label: "연고", emoji: "🧴" },
        { id: "c", label: "알약", emoji: "💊" },
        { id: "d", label: "가루약", emoji: "🧂" },
        { id: "e", label: "패치", emoji: "🩹" },
        { id: "f", label: "주사", emoji: "💉" },
      ],
      answerId: "c",
    },
    {
      id: 6,
      targetWord: "마스크",
      options: [
        { id: "a", label: "마스크", emoji: "😷" },
        { id: "b", label: "장갑", emoji: "🧤" },
        { id: "c", label: "가운", emoji: "🥼" },
        { id: "d", label: "모자", emoji: "🧢" },
        { id: "e", label: "신발커버", emoji: "🦶" },
        { id: "f", label: "안경", emoji: "👓" },
      ],
      answerId: "a",
    },
    {
      id: 7,
      targetWord: "반창고",
      options: [
        { id: "a", label: "붕대", emoji: "🩹" },
        { id: "b", label: "반창고", emoji: "🩹" },
        { id: "c", label: "소독약", emoji: "🧴" },
        { id: "d", label: "거즈", emoji: "🧻" },
        { id: "e", label: "테이프", emoji: "📎" },
        { id: "f", label: "가위", emoji: "✂️" },
      ],
      answerId: "b",
    },
    {
      id: 8,
      targetWord: "엑스레이",
      options: [
        { id: "a", label: "CT", emoji: "🔬" },
        { id: "b", label: "MRI", emoji: "🧲" },
        { id: "c", label: "엑스레이", emoji: "🦴" },
        { id: "d", label: "초음파", emoji: "📡" },
        { id: "e", label: "내시경", emoji: "🔭" },
        { id: "f", label: "현미경", emoji: "🔬" },
      ],
      answerId: "c",
    },
    {
      id: 9,
      targetWord: "의사",
      options: [
        { id: "a", label: "의사", emoji: "👨‍⚕️" },
        { id: "b", label: "간호사", emoji: "👩‍⚕️" },
        { id: "c", label: "약사", emoji: "💊" },
        { id: "d", label: "환자", emoji: "🤒" },
        { id: "e", label: "보호자", emoji: "👨‍👩‍👧" },
        { id: "f", label: "접수원", emoji: "👩‍💼" },
      ],
      answerId: "a",
    },
    {
      id: 10,
      targetWord: "구급차",
      options: [
        { id: "a", label: "경찰차", emoji: "🚓" },
        { id: "b", label: "소방차", emoji: "🚒" },
        { id: "c", label: "구급차", emoji: "🚑" },
        { id: "d", label: "버스", emoji: "🚌" },
        { id: "e", label: "택시", emoji: "🚕" },
        { id: "f", label: "헬리콥터", emoji: "🚁" },
      ],
      answerId: "c",
    },
  ],
  cafe: [
    {
      id: 1,
      targetWord: "커피",
      options: [
        { id: "a", label: "커피", emoji: "☕" },
        { id: "b", label: "차", emoji: "🍵" },
        { id: "c", label: "주스", emoji: "🧃" },
        { id: "d", label: "우유", emoji: "🥛" },
        { id: "e", label: "콜라", emoji: "🥤" },
        { id: "f", label: "물", emoji: "💧" },
      ],
      answerId: "a",
    },
    {
      id: 2,
      targetWord: "케이크",
      options: [
        { id: "a", label: "쿠키", emoji: "🍪" },
        { id: "b", label: "케이크", emoji: "🍰" },
        { id: "c", label: "마카롱", emoji: "🧁" },
        { id: "d", label: "빵", emoji: "🥐" },
        { id: "e", label: "도넛", emoji: "🍩" },
        { id: "f", label: "와플", emoji: "🧇" },
      ],
      answerId: "b",
    },
    {
      id: 3,
      targetWord: "머그컵",
      options: [
        { id: "a", label: "머그컵", emoji: "☕" },
        { id: "b", label: "텀블러", emoji: "🥤" },
        { id: "c", label: "유리컵", emoji: "🥛" },
        { id: "d", label: "종이컵", emoji: "🥛" },
        { id: "e", label: "물병", emoji: "🍾" },
        { id: "f", label: "주전자", emoji: "🫖" },
      ],
      answerId: "a",
    },
    {
      id: 4,
      targetWord: "빨대",
      options: [
        { id: "a", label: "빨대", emoji: "🥤" },
        { id: "b", label: "숟가락", emoji: "🥄" },
        { id: "c", label: "포크", emoji: "🍴" },
        { id: "d", label: "젓가락", emoji: "🥢" },
        { id: "e", label: "냅킨", emoji: "🧻" },
        { id: "f", label: "트레이", emoji: "🍽️" },
      ],
      answerId: "a",
    },
    {
      id: 5,
      targetWord: "메뉴판",
      options: [
        { id: "a", label: "영수증", emoji: "🧾" },
        { id: "b", label: "메뉴판", emoji: "📋" },
        { id: "c", label: "쿠폰", emoji: "🎫" },
        { id: "d", label: "전단지", emoji: "📄" },
        { id: "e", label: "명함", emoji: "📇" },
        { id: "f", label: "포스터", emoji: "📰" },
      ],
      answerId: "b",
    },
    {
      id: 6,
      targetWord: "샌드위치",
      options: [
        { id: "a", label: "샌드위치", emoji: "🥪" },
        { id: "b", label: "햄버거", emoji: "🍔" },
        { id: "c", label: "피자", emoji: "🍕" },
        { id: "d", label: "토스트", emoji: "🍞" },
        { id: "e", label: "베이글", emoji: "🥯" },
        { id: "f", label: "크로와상", emoji: "🥐" },
      ],
      answerId: "a",
    },
    {
      id: 7,
      targetWord: "아이스크림",
      options: [
        { id: "a", label: "아이스크림", emoji: "🍦" },
        { id: "b", label: "푸딩", emoji: "🍮" },
        { id: "c", label: "젤리", emoji: "🍬" },
        { id: "d", label: "초콜릿", emoji: "🍫" },
        { id: "e", label: "사탕", emoji: "🍭" },
        { id: "f", label: "요거트", emoji: "🥛" },
      ],
      answerId: "a",
    },
    {
      id: 8,
      targetWord: "진동벨",
      options: [
        { id: "a", label: "진동벨", emoji: "🔔" },
        { id: "b", label: "전화기", emoji: "📞" },
        { id: "c", label: "시계", emoji: "⏰" },
        { id: "d", label: "타이머", emoji: "⏱️" },
        { id: "e", label: "리모컨", emoji: "📱" },
        { id: "f", label: "계산기", emoji: "🧮" },
      ],
      answerId: "a",
    },
    {
      id: 9,
      targetWord: "의자",
      options: [
        { id: "a", label: "테이블", emoji: "🪵" },
        { id: "b", label: "의자", emoji: "🪑" },
        { id: "c", label: "소파", emoji: "🛋️" },
        { id: "d", label: "스툴", emoji: "🪑" },
        { id: "e", label: "벤치", emoji: "🪑" },
        { id: "f", label: "카운터", emoji: "🏪" },
      ],
      answerId: "b",
    },
    {
      id: 10,
      targetWord: "와이파이",
      options: [
        { id: "a", label: "와이파이", emoji: "📶" },
        { id: "b", label: "블루투스", emoji: "🔵" },
        { id: "c", label: "충전기", emoji: "🔌" },
        { id: "d", label: "콘센트", emoji: "🔌" },
        { id: "e", label: "USB", emoji: "🔌" },
        { id: "f", label: "노트북", emoji: "💻" },
      ],
      answerId: "a",
    },
  ],
  bank: [
    {
      id: 1,
      targetWord: "통장",
      options: [
        { id: "a", label: "통장", emoji: "📕" },
        { id: "b", label: "수표", emoji: "💵" },
        { id: "c", label: "카드", emoji: "💳" },
        { id: "d", label: "현금", emoji: "💰" },
        { id: "e", label: "영수증", emoji: "🧾" },
        { id: "f", label: "도장", emoji: "🔴" },
      ],
      answerId: "a",
    },
    {
      id: 2,
      targetWord: "신용카드",
      options: [
        { id: "a", label: "체크카드", emoji: "💳" },
        { id: "b", label: "신용카드", emoji: "💳" },
        { id: "c", label: "교통카드", emoji: "🚃" },
        { id: "d", label: "기프트카드", emoji: "🎁" },
        { id: "e", label: "멤버십카드", emoji: "🏷️" },
        { id: "f", label: "신분증", emoji: "🪪" },
      ],
      answerId: "b",
    },
    {
      id: 3,
      targetWord: "ATM",
      options: [
        { id: "a", label: "ATM", emoji: "🏧" },
        { id: "b", label: "자판기", emoji: "🎰" },
        { id: "c", label: "키오스크", emoji: "🖥️" },
        { id: "d", label: "복사기", emoji: "🖨️" },
        { id: "e", label: "팩스기", emoji: "📠" },
        { id: "f", label: "금고", emoji: "🔐" },
      ],
      answerId: "a",
    },
    {
      id: 4,
      targetWord: "번호표",
      options: [
        { id: "a", label: "번호표", emoji: "🎫" },
        { id: "b", label: "영수증", emoji: "🧾" },
        { id: "c", label: "쿠폰", emoji: "🎟️" },
        { id: "d", label: "신청서", emoji: "📝" },
        { id: "e", label: "명함", emoji: "📇" },
        { id: "f", label: "안내문", emoji: "📋" },
      ],
      answerId: "a",
    },
    {
      id: 5,
      targetWord: "금고",
      options: [
        { id: "a", label: "서랍", emoji: "🗄️" },
        { id: "b", label: "금고", emoji: "🔐" },
        { id: "c", label: "캐비닛", emoji: "🗃️" },
        { id: "d", label: "사물함", emoji: "🔒" },
        { id: "e", label: "창고", emoji: "🏚️" },
        { id: "f", label: "저금통", emoji: "🐷" },
      ],
      answerId: "b",
    },
    {
      id: 6,
      targetWord: "도장",
      options: [
        { id: "a", label: "도장", emoji: "🔴" },
        { id: "b", label: "펜", emoji: "🖊️" },
        { id: "c", label: "스탬프", emoji: "📮" },
        { id: "d", label: "연필", emoji: "✏️" },
        { id: "e", label: "사인", emoji: "✍️" },
        { id: "f", label: "봉투", emoji: "✉️" },
      ],
      answerId: "a",
    },
    {
      id: 7,
      targetWord: "신분증",
      options: [
        { id: "a", label: "여권", emoji: "🛂" },
        { id: "b", label: "신분증", emoji: "🪪" },
        { id: "c", label: "운전면허증", emoji: "🚗" },
        { id: "d", label: "학생증", emoji: "🎓" },
        { id: "e", label: "사원증", emoji: "🏢" },
        { id: "f", label: "건강보험증", emoji: "🏥" },
      ],
      answerId: "b",
    },
    {
      id: 8,
      targetWord: "만원",
      options: [
        { id: "a", label: "천원", emoji: "💵" },
        { id: "b", label: "오천원", emoji: "💵" },
        { id: "c", label: "만원", emoji: "💵" },
        { id: "d", label: "오만원", emoji: "💵" },
        { id: "e", label: "백원", emoji: "🪙" },
        { id: "f", label: "오백원", emoji: "🪙" },
      ],
      answerId: "c",
    },
    {
      id: 9,
      targetWord: "서류",
      options: [
        { id: "a", label: "서류", emoji: "📄" },
        { id: "b", label: "책", emoji: "📚" },
        { id: "c", label: "신문", emoji: "📰" },
        { id: "d", label: "잡지", emoji: "📖" },
        { id: "e", label: "전단지", emoji: "📃" },
        { id: "f", label: "포스터", emoji: "🖼️" },
      ],
      answerId: "a",
    },
    {
      id: 10,
      targetWord: "계산기",
      options: [
        { id: "a", label: "계산기", emoji: "🧮" },
        { id: "b", label: "전화기", emoji: "📞" },
        { id: "c", label: "컴퓨터", emoji: "💻" },
        { id: "d", label: "태블릿", emoji: "📱" },
        { id: "e", label: "프린터", emoji: "🖨️" },
        { id: "f", label: "시계", emoji: "⏰" },
      ],
      answerId: "a",
    },
  ],
  park: [
    {
      id: 1,
      targetWord: "나무",
      options: [
        { id: "a", label: "나무", emoji: "🌳" },
        { id: "b", label: "꽃", emoji: "🌸" },
        { id: "c", label: "풀", emoji: "🌿" },
        { id: "d", label: "돌", emoji: "🪨" },
        { id: "e", label: "흙", emoji: "🟤" },
        { id: "f", label: "물", emoji: "💧" },
      ],
      answerId: "a",
    },
    {
      id: 2,
      targetWord: "벤치",
      options: [
        { id: "a", label: "벤치", emoji: "🪑" },
        { id: "b", label: "그네", emoji: "🎢" },
        { id: "c", label: "미끄럼틀", emoji: "🛝" },
        { id: "d", label: "시소", emoji: "⚖️" },
        { id: "e", label: "정글짐", emoji: "🏗️" },
        { id: "f", label: "모래터", emoji: "🏖️" },
      ],
      answerId: "a",
    },
    {
      id: 3,
      targetWord: "자전거",
      options: [
        { id: "a", label: "자전거", emoji: "🚲" },
        { id: "b", label: "킥보드", emoji: "🛴" },
        { id: "c", label: "롤러블레이드", emoji: "⛸️" },
        { id: "d", label: "스케이트보드", emoji: "🛹" },
        { id: "e", label: "유모차", emoji: "👶" },
        { id: "f", label: "휠체어", emoji: "🦽" },
      ],
      answerId: "a",
    },
    {
      id: 4,
      targetWord: "강아지",
      options: [
        { id: "a", label: "강아지", emoji: "🐕" },
        { id: "b", label: "고양이", emoji: "🐈" },
        { id: "c", label: "새", emoji: "🐦" },
        { id: "d", label: "다람쥐", emoji: "🐿️" },
        { id: "e", label: "토끼", emoji: "🐇" },
        { id: "f", label: "물고기", emoji: "🐟" },
      ],
      answerId: "a",
    },
    {
      id: 5,
      targetWord: "분수대",
      options: [
        { id: "a", label: "분수대", emoji: "⛲" },
        { id: "b", label: "연못", emoji: "🏞️" },
        { id: "c", label: "수도꼭지", emoji: "🚰" },
        { id: "d", label: "샤워기", emoji: "🚿" },
        { id: "e", label: "호스", emoji: "🧯" },
        { id: "f", label: "빗물받이", emoji: "🌧️" },
      ],
      answerId: "a",
    },
    {
      id: 6,
      targetWord: "풍선",
      options: [
        { id: "a", label: "풍선", emoji: "🎈" },
        { id: "b", label: "공", emoji: "⚽" },
        { id: "c", label: "연", emoji: "🪁" },
        { id: "d", label: "비눗방울", emoji: "🫧" },
        { id: "e", label: "프리스비", emoji: "🥏" },
        { id: "f", label: "배드민턴", emoji: "🏸" },
      ],
      answerId: "a",
    },
    {
      id: 7,
      targetWord: "돗자리",
      options: [
        { id: "a", label: "돗자리", emoji: "🧺" },
        { id: "b", label: "텐트", emoji: "⛺" },
        { id: "c", label: "의자", emoji: "🪑" },
        { id: "d", label: "파라솔", emoji: "⛱️" },
        { id: "e", label: "캠핑카", emoji: "🚐" },
        { id: "f", label: "침낭", emoji: "🛏️" },
      ],
      answerId: "a",
    },
    {
      id: 8,
      targetWord: "해",
      options: [
        { id: "a", label: "해", emoji: "☀️" },
        { id: "b", label: "달", emoji: "🌙" },
        { id: "c", label: "별", emoji: "⭐" },
        { id: "d", label: "구름", emoji: "☁️" },
        { id: "e", label: "무지개", emoji: "🌈" },
        { id: "f", label: "번개", emoji: "⚡" },
      ],
      answerId: "a",
    },
    {
      id: 9,
      targetWord: "나비",
      options: [
        { id: "a", label: "나비", emoji: "🦋" },
        { id: "b", label: "벌", emoji: "🐝" },
        { id: "c", label: "잠자리", emoji: "🪰" },
        { id: "d", label: "무당벌레", emoji: "🐞" },
        { id: "e", label: "개미", emoji: "🐜" },
        { id: "f", label: "메뚜기", emoji: "🦗" },
      ],
      answerId: "a",
    },
    {
      id: 10,
      targetWord: "쓰레기통",
      options: [
        { id: "a", label: "쓰레기통", emoji: "🗑️" },
        { id: "b", label: "재활용함", emoji: "♻️" },
        { id: "c", label: "우체통", emoji: "📮" },
        { id: "d", label: "소화기", emoji: "🧯" },
        { id: "e", label: "가로등", emoji: "🏮" },
        { id: "f", label: "표지판", emoji: "🪧" },
      ],
      answerId: "a",
    },
  ],
  mart: [
    {
      id: 1,
      targetWord: "장바구니",
      options: [
        { id: "a", label: "장바구니", emoji: "🧺" },
        { id: "b", label: "카트", emoji: "🛒" },
        { id: "c", label: "박스", emoji: "📦" },
        { id: "d", label: "봉투", emoji: "🛍️" },
        { id: "e", label: "가방", emoji: "👜" },
        { id: "f", label: "지갑", emoji: "👛" },
      ],
      answerId: "a",
    },
    {
      id: 2,
      targetWord: "사과",
      options: [
        { id: "a", label: "사과", emoji: "🍎" },
        { id: "b", label: "배", emoji: "🍐" },
        { id: "c", label: "포도", emoji: "🍇" },
        { id: "d", label: "바나나", emoji: "🍌" },
        { id: "e", label: "오렌지", emoji: "🍊" },
        { id: "f", label: "수박", emoji: "🍉" },
      ],
      answerId: "a",
    },
    {
      id: 3,
      targetWord: "우유",
      options: [
        { id: "a", label: "우유", emoji: "🥛" },
        { id: "b", label: "주스", emoji: "🧃" },
        { id: "c", label: "물", emoji: "💧" },
        { id: "d", label: "탄산수", emoji: "🥤" },
        { id: "e", label: "요거트", emoji: "🍦" },
        { id: "f", label: "아이스크림", emoji: "🍨" },
      ],
      answerId: "a",
    },
    {
      id: 4,
      targetWord: "빵",
      options: [
        { id: "a", label: "빵", emoji: "🍞" },
        { id: "b", label: "케이크", emoji: "🍰" },
        { id: "c", label: "쿠키", emoji: "🍪" },
        { id: "d", label: "과자", emoji: "🍘" },
        { id: "e", label: "떡", emoji: "🍡" },
        { id: "f", label: "라면", emoji: "🍜" },
      ],
      answerId: "a",
    },
    {
      id: 5,
      targetWord: "계란",
      options: [
        { id: "a", label: "계란", emoji: "🥚" },
        { id: "b", label: "두부", emoji: "🫘" },
        { id: "c", label: "치즈", emoji: "🧀" },
        { id: "d", label: "버터", emoji: "🧈" },
        { id: "e", label: "소시지", emoji: "🌭" },
        { id: "f", label: "햄", emoji: "🥓" },
      ],
      answerId: "a",
    },
    {
      id: 6,
      targetWord: "당근",
      options: [
        { id: "a", label: "당근", emoji: "🥕" },
        { id: "b", label: "감자", emoji: "🥔" },
        { id: "c", label: "양파", emoji: "🧅" },
        { id: "d", label: "고구마", emoji: "🍠" },
        { id: "e", label: "오이", emoji: "🥒" },
        { id: "f", label: "토마토", emoji: "🍅" },
      ],
      answerId: "a",
    },
    {
      id: 7,
      targetWord: "생선",
      options: [
        { id: "a", label: "생선", emoji: "🐟" },
        { id: "b", label: "고기", emoji: "🥩" },
        { id: "c", label: "닭고기", emoji: "🍗" },
        { id: "d", label: "새우", emoji: "🦐" },
        { id: "e", label: "조개", emoji: "🦪" },
        { id: "f", label: "게", emoji: "🦀" },
      ],
      answerId: "a",
    },
    {
      id: 8,
      targetWord: "영수증",
      options: [
        { id: "a", label: "영수증", emoji: "🧾" },
        { id: "b", label: "쿠폰", emoji: "🎫" },
        { id: "c", label: "전단지", emoji: "📄" },
        { id: "d", label: "포인트카드", emoji: "💳" },
        { id: "e", label: "가격표", emoji: "🏷️" },
        { id: "f", label: "바코드", emoji: "📊" },
      ],
      answerId: "a",
    },
    {
      id: 9,
      targetWord: "계산대",
      options: [
        { id: "a", label: "계산대", emoji: "🏪" },
        { id: "b", label: "진열대", emoji: "🗄️" },
        { id: "c", label: "냉동고", emoji: "🧊" },
        { id: "d", label: "선반", emoji: "📚" },
        { id: "e", label: "카운터", emoji: "🛎️" },
        { id: "f", label: "안내데스크", emoji: "ℹ️" },
      ],
      answerId: "a",
    },
    {
      id: 10,
      targetWord: "지갑",
      options: [
        { id: "a", label: "지갑", emoji: "👛" },
        { id: "b", label: "가방", emoji: "👜" },
        { id: "c", label: "파우치", emoji: "👝" },
        { id: "d", label: "주머니", emoji: "🧳" },
        { id: "e", label: "케이스", emoji: "📱" },
        { id: "f", label: "통장", emoji: "📕" },
      ],
      answerId: "a",
    },
  ],
};
