// src/constants/writingData.ts
import { PlaceType } from "./trainingData";

export interface WritingWord {
  id: number;
  hint: string;
  emoji: string;
  answer: string;
  category: string;
  strokes: number; // ✅ 판정을 위한 획수 데이터
}

export const WRITING_WORDS: Record<PlaceType, WritingWord[]> = {
  home: [
    {
      id: 1,
      hint: "물을 끓이는 도구",
      emoji: "🥘",
      answer: "냄비",
      category: "주방",
      strokes: 10,
    },
    {
      id: 2,
      hint: "잠을 자는 가구",
      emoji: "🛏️",
      answer: "침대",
      category: "가구",
      strokes: 11,
    },
    {
      id: 3,
      hint: "옷을 보관하는 곳",
      emoji: "👗",
      answer: "옷장",
      category: "가구",
      strokes: 11,
    },
    {
      id: 4,
      hint: "문을 여는 도구",
      emoji: "🔑",
      answer: "열쇠",
      category: "생활",
      strokes: 8,
    },
    {
      id: 5,
      hint: "얼굴을 보는 물건",
      emoji: "🪞",
      answer: "거울",
      category: "생활",
      strokes: 10,
    },
    {
      id: 6,
      hint: "추울 때 덮는 것",
      emoji: "☁️",
      answer: "이불",
      category: "침구",
      strokes: 7,
    },
    {
      id: 7,
      hint: "TV 채널을 바꾸는 것",
      emoji: "📺",
      answer: "리모컨",
      category: "가전",
      strokes: 15,
    },
    {
      id: 8,
      hint: "빨래를 하는 기계",
      emoji: "🧺",
      answer: "세탁기",
      category: "가전",
      strokes: 16,
    },
  ],
  hospital: [
    {
      id: 1,
      hint: "아플 때 먹는 것",
      emoji: "💊",
      answer: "약",
      category: "의료",
      strokes: 6,
    },
    {
      id: 2,
      hint: "체온을 재는 도구",
      emoji: "🌡️",
      answer: "체온계",
      category: "의료",
      strokes: 15,
    },
    {
      id: 3,
      hint: "환자를 치료하는 사람",
      emoji: "👨‍⚕️",
      answer: "의사",
      category: "직업",
      strokes: 10,
    },
    {
      id: 4,
      hint: "주사를 놓는 도구",
      emoji: "💉",
      answer: "주사기",
      category: "의료",
      strokes: 10,
    },
    {
      id: 5,
      hint: "상처에 붙이는 것",
      emoji: "🩹",
      answer: "반창고",
      category: "의료",
      strokes: 16,
    },
    {
      id: 6,
      hint: "환자를 옮기는 의자",
      emoji: "🦽",
      answer: "휠체어",
      category: "의료",
      strokes: 18,
    },
    {
      id: 7,
      hint: "코와 입을 가리는 것",
      emoji: "😷",
      answer: "마스크",
      category: "위생",
      strokes: 12,
    },
    {
      id: 8,
      hint: "의사가 쓰는 처방",
      emoji: "📋",
      answer: "처방전",
      category: "서류",
      strokes: 18,
    },
  ],
  cafe: [
    {
      id: 1,
      hint: "따뜻한 음료",
      emoji: "☕",
      answer: "커피",
      category: "음료",
      strokes: 8,
    },
    {
      id: 2,
      hint: "음료를 담는 용기",
      emoji: "🥛",
      answer: "컵",
      category: "용기",
      strokes: 4,
    },
    {
      id: 3,
      hint: "빵과 크림으로 만든 것",
      emoji: "🍰",
      answer: "케이크",
      category: "디저트",
      strokes: 13,
    },
    {
      id: 4,
      hint: "음료에 꽂는 것",
      emoji: "🥤",
      answer: "빨대",
      category: "용품",
      strokes: 9,
    },
    {
      id: 5,
      hint: "주문 후 받는 것",
      emoji: "🔔",
      answer: "진동벨",
      category: "용품",
      strokes: 16,
    },
    {
      id: 6,
      hint: "앉는 가구",
      emoji: "🪑",
      answer: "의자",
      category: "가구",
      strokes: 10,
    },
    {
      id: 7,
      hint: "메뉴를 보는 것",
      emoji: "📜",
      answer: "메뉴판",
      category: "용품",
      strokes: 13,
    },
    {
      id: 8,
      hint: "결제 후 받는 것",
      emoji: "🧾",
      answer: "영수증",
      category: "서류",
      strokes: 16,
    },
  ],
  bank: [
    {
      id: 1,
      hint: "돈을 넣는 책",
      emoji: "📕",
      answer: "통장",
      category: "금융",
      strokes: 11,
    },
    {
      id: 2,
      hint: "결제할 때 쓰는 것",
      emoji: "💳",
      answer: "카드",
      category: "금융",
      strokes: 8,
    },
    {
      id: 3,
      hint: "현금을 찾는 기계",
      emoji: "🏧",
      answer: "ATM",
      category: "기기",
      strokes: 6,
    },
    {
      id: 4,
      hint: "기다릴 때 받는 것",
      emoji: "🎫",
      answer: "번호표",
      category: "서류",
      strokes: 15,
    },
    {
      id: 5,
      hint: "귀중품 보관함",
      emoji: "🔐",
      answer: "금고",
      category: "보관",
      strokes: 10,
    },
    {
      id: 6,
      hint: "서류에 찍는 것",
      emoji: "⭕",
      answer: "도장",
      category: "문구",
      strokes: 10,
    },
    {
      id: 7,
      hint: "신원을 확인하는 것",
      emoji: "🆔",
      answer: "신분증",
      category: "서류",
      strokes: 16,
    },
    {
      id: 8,
      hint: "숫자를 계산하는 것",
      emoji: "🧮",
      answer: "계산기",
      category: "기기",
      strokes: 18,
    },
  ],
  park: [
    {
      id: 1,
      hint: "키가 크고 잎이 있는 것",
      emoji: "🌳",
      answer: "나무",
      category: "자연",
      strokes: 8,
    },
    {
      id: 2,
      hint: "예쁜 색의 식물",
      emoji: "🌸",
      answer: "꽃",
      category: "자연",
      strokes: 6,
    },
    {
      id: 3,
      hint: "앉어서 쉬는 곳",
      emoji: "🪵",
      answer: "벤치",
      category: "시설",
      strokes: 11,
    },
    {
      id: 4,
      hint: "두 바퀴로 타는 것",
      emoji: "🚲",
      answer: "자전거",
      category: "이동",
      strokes: 15,
    },
    {
      id: 5,
      hint: "물이 솟아오르는 곳",
      emoji: "⛲",
      answer: "분수대",
      category: "시설",
      strokes: 18,
    },
    {
      id: 6,
      hint: "하늘을 나는 곤충",
      emoji: "🦋",
      answer: "나비",
      category: "동물",
      strokes: 10,
    },
    {
      id: 7,
      hint: "공중에 띄우는 것",
      emoji: "🪁",
      answer: "연",
      category: "놀이",
      strokes: 4,
    },
    {
      id: 8,
      hint: "낮에 빛나는 것",
      emoji: "☀️",
      answer: "해",
      category: "자연",
      strokes: 4,
    },
  ],
  mart: [
    {
      id: 1,
      hint: "빨간 과일",
      emoji: "🍎",
      answer: "사과",
      category: "과일",
      strokes: 10,
    },
    {
      id: 2,
      hint: "물건을 담는 바구니",
      emoji: "🛒",
      answer: "카트",
      category: "용품",
      strokes: 7,
    },
    {
      id: 3,
      hint: "하얀 음료",
      emoji: "🥛",
      answer: "우유",
      category: "음료",
      strokes: 9,
    },
    {
      id: 4,
      hint: "주황색 채소",
      emoji: "🥕",
      answer: "당근",
      category: "채소",
      strokes: 11,
    },
    {
      id: 5,
      hint: "돈을 내는 곳",
      emoji: "🏪",
      answer: "계산대",
      category: "시설",
      strokes: 15,
    },
    {
      id: 6,
      hint: "노란 과일",
      emoji: "🍌",
      answer: "바나나",
      category: "과일",
      strokes: 16,
    },
    {
      id: 7,
      hint: "둥근 알",
      emoji: "🥚",
      answer: "계란",
      category: "식품",
      strokes: 11,
    },
    {
      id: 8,
      hint: "돈을 넣는 곳",
      emoji: "👛",
      answer: "지갑",
      category: "용품",
      strokes: 10,
    },
  ],
};
