import { PlaceType } from "./trainingData";

export const SPEECH_REPETITION_PROTOCOLS: Record<PlaceType, any> = {
  home: [
    { id: 1, text: "방", points: 2, duration: 10 },
    { id: 2, text: "창문", points: 2, duration: 10 },
    { id: 3, text: "냉장고", points: 2, duration: 10 },
    { id: 4, text: "텔레비전", points: 2, duration: 10 },
    { id: 5, text: "따뜻한 안방", points: 4, duration: 10 },
    { id: 6, text: "깨끗한 주방", points: 4, duration: 10 },
    { id: 7, text: "창문 너머로 햇살이 비쳤다", points: 8, duration: 12 },
    { id: 8, text: "보글보글 끓는 된장 찌개", points: 8, duration: 12 },
    { id: 9, text: "가족들이 거실에 모두 모였다", points: 10, duration: 15 },
    {
      id: 10,
      text: "새로 산 세탁기가 베란다에 놓여 있다",
      points: 12,
      duration: 15,
    },
  ],
  hospital: [
    { id: 1, text: "약", points: 2, duration: 10 },
    { id: 2, text: "의사", points: 2, duration: 10 },
    { id: 3, text: "주사실", points: 2, duration: 10 },
    { id: 4, text: "처방전", points: 2, duration: 10 },
    { id: 5, text: "친절한 간호사", points: 4, duration: 10 },
    { id: 6, text: "혈압을 측정 했다", points: 6, duration: 10 },
    { id: 7, text: "접수처에 신분증을 제출 하세요", points: 8, duration: 12 },
    { id: 8, text: "식후 삼십 분에 복용 하세요", points: 10, duration: 12 },
    { id: 9, text: "검사 결과는 다음 주에 나옵니다", points: 10, duration: 15 },
    {
      id: 10,
      text: "무리한 운동은 피하고 충분히 휴식 하세요",
      points: 12,
      duration: 15,
    },
  ],
  cafe: [
    { id: 1, text: "컵", points: 2, duration: 10 },
    { id: 2, text: "커피", points: 2, duration: 10 },
    { id: 3, text: "우유", points: 2, duration: 10 },
    { id: 4, text: "진동벨", points: 2, duration: 10 },
    { id: 5, text: "시원한 콜라", points: 4, duration: 10 },
    { id: 6, text: "주문이 완료 되었다", points: 6, duration: 10 },
    { id: 7, text: "설탕은 넣지 말고 가져 오세요", points: 10, duration: 12 },
    { id: 8, text: "따뜻한 아메리카노 두 잔 주세요", points: 10, duration: 12 },
    {
      id: 9,
      text: "영수증은 버리지 말고 챙겨 주세요",
      points: 10,
      duration: 15,
    },
    {
      id: 10,
      text: "창가 쪽 자리에 앉아서 책을 읽었다",
      points: 12,
      duration: 15,
    },
  ],
  bank: [
    { id: 1, text: "돈", points: 2, duration: 10 },
    { id: 2, text: "통장", points: 2, duration: 10 },
    { id: 3, text: "카드", points: 2, duration: 10 },
    { id: 4, text: "비밀번호", points: 2, duration: 10 },
    { id: 5, text: "높은 이자", points: 4, duration: 10 },
    { id: 6, text: "번호표를 뽑았다", points: 6, duration: 10 },
    { id: 7, text: "현금을 인출기에 넣고 기다렸다", points: 10, duration: 12 },
    { id: 8, text: "도장 대신 서명을 해도 됩니다", points: 10, duration: 12 },
    {
      id: 9,
      text: "잔액이 부족하여 결제가 되지 않았다",
      points: 12,
      duration: 15,
    },
    {
      id: 10,
      text: "보이스 피싱 전화를 받으면 바로 신고 하세요",
      points: 14,
      duration: 15,
    },
  ],
  park: [
    { id: 1, text: "꽃", points: 2, duration: 10 },
    { id: 2, text: "나무", points: 2, duration: 10 },
    { id: 3, text: "강아지", points: 2, duration: 10 },
    { id: 4, text: "산책로", points: 2, duration: 10 },
    { id: 5, text: "푸른 잔디", points: 4, duration: 10 },
    { id: 6, text: "벤치에 앉아 쉬었다", points: 8, duration: 10 },
    { id: 7, text: "나무 위에 새가 노래 부른다", points: 10, duration: 12 },
    { id: 8, text: "자전거를 탈 때는 헬멧을 쓰세요", points: 10, duration: 12 },
    {
      id: 9,
      text: "공원 바닥에 쓰레기를 버리지 마세요",
      points: 10,
      duration: 15,
    },
    {
      id: 10,
      text: "아이들이 놀이터에서 즐겁게 뛰어 놀고 있다",
      points: 14,
      duration: 15,
    },
  ],
  mart: [
    { id: 1, text: "콩", points: 2, duration: 10 },
    { id: 2, text: "사과", points: 2, duration: 10 },
    { id: 3, text: "장바구니", points: 2, duration: 10 },
    { id: 4, text: "계산대", points: 2, duration: 10 },
    { id: 5, text: "싱싱한 오이", points: 4, duration: 10 },
    { id: 6, text: "가격을 확인 했다", points: 6, duration: 10 },
    { id: 7, text: "카트에 배추 두 통을 담았다", points: 10, duration: 12 },
    { id: 8, text: "거스름돈 천 원을 더 받았다", points: 10, duration: 12 },
    {
      id: 9,
      text: "계란 한 판을 깨지지 않게 담으세요",
      points: 12,
      duration: 15,
    },
    {
      id: 10,
      text: "포인트 카드를 만들면 적립을 해 드립니다",
      points: 14,
      duration: 15,
    },
  ],
};
